spring:
  config:
    import: optional:file:./config/application.yaml

  application:
    name: otp-auth-service-hw

  datasource:
    url: ""
    username: ""
    password: ""
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yaml

server:
  port: 8080

app:
  otp:
    default-config:
      code-length: 6
      ttl-seconds: 300

  jwt:
    secret: ""
    expiration-ms: 3600000

  crypto:
    otp-code:
      secret: ""

  job:
    otp-expiration:
      fixed-delay-ms: 60000
      initial-delay-ms: 10000

    notification-outbox:
      fixed-delay-ms: 5000
      initial-delay-ms: 5000
      batch-size: 10
      max-attempts: 3
      max-error-message-length: 1000

  notification:
    file:
      path: otp-codes.txt

    email:
      username: ""
      password: ""
      from: ""
      host: ""
      port: 587
      auth: true
      starttls-enable: true

    sms:
      host: localhost
      port: 2775
      system-id: ""
      password: ""
      system-type: OTP
      source-address: OTPService

    telegram:
      bot-token: ""
      chat-id: ""

logging:
  level:
    root: info
    ru.miphi: debug
